.PHONY: clean All

All:
	@echo "----------Building project:[ FreewayAC - Release ]----------"
	@$(MAKE) -f  "FreewayAC.mk"
clean:
	@echo "----------Cleaning project:[ FreewayAC - Release ]----------"
	@$(MAKE) -f  "FreewayAC.mk" clean
